import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Footer,
  Header,
  PageNumber,
  AlignmentType,
} from 'docx';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { fmtClock, speakerOf } from '../utils/transcript.js';

/**
 * Exports: a neutral document model ({ title, subtitle, blocks }) rendered to TXT / PDF / DOCX,
 * plus CSV for action items. All branded "LifeOS".
 *
 * Note: PDF uses the built-in Helvetica font, which only covers Latin-1 characters. Other
 * scripts are replaced with "?" in PDFs; use DOCX for non-Latin transcripts.
 */

const BRAND = 'LifeOS';
const INDIGO = rgb(0.31, 0.27, 0.9);

export const EXPORT_MATRIX = {
  transcript: ['txt', 'pdf', 'docx'],
  summary: ['pdf', 'docx', 'txt'],
  minutes: ['pdf', 'docx', 'txt'],
  'action-items': ['csv', 'pdf', 'docx'],
};

const CONTENT_TYPES = {
  txt: 'text/plain; charset=utf-8',
  csv: 'text/csv; charset=utf-8',
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
};

const slug = (s) => String(s || 'meeting').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'meeting';

function whenLine(meeting) {
  const tz = meeting.timezone || 'UTC';
  const d = new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeStyle: 'short', timeZone: tz }).format(meeting.startedAt || meeting.startAt);
  return `${d} (${tz})`;
}

// ── document builders ───────────────────────────────────────────────────

/** Minimal Markdown → blocks (headings, bullets, paragraphs, **bold** stripped). */
export function markdownToBlocks(md = '') {
  const blocks = [];
  for (const raw of md.split('\n')) {
    const line = raw.trimEnd();
    if (!line.trim()) continue;
    const clean = (t) => t.replace(/\*\*(.+?)\*\*/g, '$1').replace(/_(.+?)_/g, '$1');
    if (line.startsWith('### ')) blocks.push({ type: 'h3', text: clean(line.slice(4)) });
    else if (line.startsWith('## ')) blocks.push({ type: 'h2', text: clean(line.slice(3)) });
    else if (line.startsWith('# ')) blocks.push({ type: 'h1', text: clean(line.slice(2)) });
    else if (/^[-*]\s+/.test(line)) blocks.push({ type: 'bullet', text: clean(line.replace(/^[-*]\s+/, '')) });
    else blocks.push({ type: 'p', text: clean(line) });
  }
  return blocks;
}

function docFor(kind, { meeting, segments = [], actionItems = [] }) {
  const base = { subtitle: `${meeting.title} — ${whenLine(meeting)}` };
  if (kind === 'transcript') {
    return {
      ...base,
      title: 'Meeting Transcript',
      blocks: segments.length
        ? segments.map((s) => ({ type: 'p', text: `[${fmtClock(s.startMs)}] ${speakerOf(s)}: ${s.text}` }))
        : [{ type: 'p', text: 'No transcript available.' }],
    };
  }
  if (kind === 'summary') {
    const s = meeting.summary || {};
    const list = (title, arr) => (arr?.length ? [{ type: 'h2', text: title }, ...arr.map((t) => ({ type: 'bullet', text: t }))] : []);
    return {
      ...base,
      title: 'AI Meeting Summary',
      blocks: [
        { type: 'h2', text: 'Executive Summary' },
        { type: 'p', text: s.executiveSummary || 'No summary has been generated yet.' },
        ...list('Key Discussion Points', s.keyPoints),
        ...list('Decisions', s.decisions),
        ...list('Questions for Follow-up', s.questions),
        ...list('Next Steps', s.nextSteps),
        ...list('Important Topics', s.topics),
        { type: 'p', text: 'Generated by AI from the meeting transcript. Review before relying on it.' },
      ],
    };
  }
  if (kind === 'minutes') {
    return { ...base, title: 'Meeting Minutes', blocks: markdownToBlocks(meeting.minutes?.content || 'Minutes have not been generated yet.') };
  }
  const due = (a) => (a.deadline ? a.deadline.toISOString().slice(0, 10) : a.deadlineText || '—');
  return {
    ...base,
    title: 'Action Items',
    blocks: actionItems.length
      ? actionItems.map((a) => ({ type: 'bullet', text: `${a.task} — ${a.assigneeName || 'Unassigned'} | Due: ${due(a)} | ${a.priority} | ${a.status.replace('_', ' ')}` }))
      : [{ type: 'p', text: 'No action items.' }],
  };
}

// ── renderers ───────────────────────────────────────────────────────────

function toTxt(doc) {
  const lines = [`${BRAND} — ${doc.title}`, doc.subtitle, ''];
  for (const b of doc.blocks) {
    if (b.type === 'h1' || b.type === 'h2') lines.push('', b.text.toUpperCase());
    else if (b.type === 'h3') lines.push('', b.text);
    else if (b.type === 'bullet') lines.push(`  - ${b.text}`);
    else lines.push(b.text);
  }
  return Buffer.from(lines.join('\n') + '\n', 'utf8');
}

async function toPdf(doc) {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const W = 595;
  const H = 842;
  const M = 50;
  const maxW = W - 2 * M;

  const cache = new Map();
  const safe = (t) =>
    [...String(t)]
      .map((ch) => {
        if (cache.has(ch)) return cache.get(ch);
        let out = ch;
        try {
          font.encodeText(ch);
        } catch {
          out = ch === '\n' || ch === '\t' ? ' ' : '?';
        }
        cache.set(ch, out);
        return out;
      })
      .join('');

  function wrap(text, f, size, width) {
    const words = safe(text).split(/\s+/).filter(Boolean);
    const lines = [];
    let cur = '';
    for (const w of words) {
      const trial = cur ? `${cur} ${w}` : w;
      if (f.widthOfTextAtSize(trial, size) <= width) cur = trial;
      else {
        if (cur) lines.push(cur);
        // hard-split a single very long token
        let rest = w;
        while (f.widthOfTextAtSize(rest, size) > width) {
          let n = rest.length;
          while (n > 1 && f.widthOfTextAtSize(rest.slice(0, n), size) > width) n -= 1;
          lines.push(rest.slice(0, n));
          rest = rest.slice(n);
        }
        cur = rest;
      }
    }
    if (cur) lines.push(cur);
    return lines.length ? lines : [''];
  }

  let page;
  let y;
  const newPage = () => {
    page = pdf.addPage([W, H]);
    page.drawText(BRAND, { x: M, y: H - 32, size: 12, font: bold, color: INDIGO });
    page.drawLine({ start: { x: M, y: H - 40 }, end: { x: W - M, y: H - 40 }, thickness: 0.6, color: rgb(0.85, 0.85, 0.9) });
    y = H - 64;
  };
  const ensure = (need) => {
    if (y - need < M + 20) newPage();
  };
  const draw = (text, { f = font, size = 10.5, indent = 0, gap = 4, color = rgb(0.1, 0.1, 0.15), bullet = false } = {}) => {
    const lh = size * 1.35;
    const lines = wrap(text, f, size, maxW - indent - (bullet ? 12 : 0));
    lines.forEach((ln, i) => {
      ensure(lh);
      if (bullet && i === 0) page.drawText('-', { x: M + indent, y, size, font: f, color });
      page.drawText(ln, { x: M + indent + (bullet ? 12 : 0), y, size, font: f, color });
      y -= lh;
    });
    y -= gap;
  };

  newPage();
  draw(doc.title, { f: bold, size: 20, gap: 2, color: INDIGO });
  draw(doc.subtitle, { size: 10, gap: 12, color: rgb(0.4, 0.4, 0.5) });
  for (const b of doc.blocks) {
    if (b.type === 'h1') draw(b.text, { f: bold, size: 16, gap: 6 });
    else if (b.type === 'h2') { y -= 6; draw(b.text, { f: bold, size: 13, gap: 4 }); }
    else if (b.type === 'h3') draw(b.text, { f: bold, size: 11.5, gap: 3, indent: 4 });
    else if (b.type === 'bullet') draw(b.text, { bullet: true, indent: 6, gap: 2 });
    else draw(b.text, { gap: 3 });
  }

  const pages = pdf.getPages();
  pages.forEach((p, i) => {
    p.drawText(`Generated by ${BRAND} · Page ${i + 1} of ${pages.length}`, { x: M, y: 28, size: 8, font, color: rgb(0.5, 0.5, 0.6) });
  });
  return Buffer.from(await pdf.save());
}

async function toDocx(doc) {
  const para = (b) => {
    switch (b.type) {
      case 'h1': return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(b.text)] });
      case 'h2': return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 200 }, children: [new TextRun(b.text)] });
      case 'h3': return new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun(b.text)] });
      case 'bullet': return new Paragraph({ bullet: { level: 0 }, children: [new TextRun(b.text)] });
      default: return new Paragraph({ spacing: { after: 80 }, children: [new TextRun(b.text)] });
    }
  };
  const d = new Document({
    creator: BRAND,
    title: doc.title,
    sections: [
      {
        headers: { default: new Header({ children: [new Paragraph({ children: [new TextRun({ text: BRAND, bold: true, color: '4F46E5', size: 24 })] })] }) },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: `Generated by ${BRAND} · Page `, size: 16, color: '888888' }), new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '888888' })],
              }),
            ],
          }),
        },
        children: [
          new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: doc.title, color: '4F46E5' })] }),
          new Paragraph({ spacing: { after: 240 }, children: [new TextRun({ text: doc.subtitle, color: '666666', size: 20 })] }),
          ...doc.blocks.map(para),
        ],
      },
    ],
  });
  return Packer.toBuffer(d);
}

/** Neutralises spreadsheet formula injection (=, +, -, @ at the start of a cell). */
const csvCell = (v) => {
  let s = v == null ? '' : String(v);
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  return `"${s.replace(/"/g, '""')}"`;
};

function toCsv(meeting, actionItems) {
  const head = ['Meeting', 'Meeting date', 'Task', 'Assigned to', 'Deadline', 'Priority', 'Status'];
  const date = (meeting.startedAt || meeting.startAt).toISOString().slice(0, 10);
  const rows = actionItems.map((a) => [
    meeting.title,
    date,
    a.task,
    a.assigneeName || '',
    a.deadline ? a.deadline.toISOString().slice(0, 10) : a.deadlineText || '',
    a.priority,
    a.status,
  ]);
  return Buffer.from('\uFEFF' + [head, ...rows].map((r) => r.map(csvCell).join(',')).join('\r\n') + '\r\n', 'utf8');
}

export function isExportAllowed(kind, format) {
  return Boolean(EXPORT_MATRIX[kind]?.includes(format));
}

export async function buildExport(kind, format, data) {
  const { meeting } = data;
  let buffer;
  if (format === 'csv') buffer = toCsv(meeting, data.actionItems || []);
  else {
    const doc = docFor(kind, data);
    if (format === 'txt') buffer = toTxt(doc);
    else if (format === 'pdf') buffer = await toPdf(doc);
    else buffer = await toDocx(doc);
  }
  const date = (meeting.startedAt || meeting.startAt).toISOString().slice(0, 10);
  return { buffer, contentType: CONTENT_TYPES[format], filename: `${slug(meeting.title)}-${kind}-${date}.${format}` };
}
